projects:
  hepimusic:
    schemaPath: amplify/backend/api/hepimusic/build/schema.graphql
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: ap-south-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
